FROM apache/airflow:2.11.0-python3.12

USER root

RUN apt-get update && \
    apt-get install -y gcc python3-dev openjdk-17-jdk && \
    apt-get clean

ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64

USER airflow

RUN pip install minio apache-airflow apache-airflow-providers-apache-spark pyspark==3.5.2
